INSERT INTO programa (nombre, version) VALUES
("Application Server", "9i"),
("Oracle Database", "8i"),
("Database", "91"),
("Database", "10g"),
("Developer", "6i"),
("Access", "97"),
("Access", "2000"),
("Access", "XP"),
("Windows", "98"),
("Windows", "XP Professional"),
("Windows", "XP Home Edition"),
("Windows", "2003 Server"),
("Norton Internet Security", "2004"),
("Freddy Hardest", NULL),
("Paradox", "2"),
("C++ Builder", "5.5"),
("DB/2", "2.0"),
("OS/2", "1.0"),
("JBuilder", "X"),
("La Prision", "1.0");